CREATE TABLE IF NOT EXISTS purchase_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    drug_name TEXT NOT NULL,
    purchase_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    buyer TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    total_amount REAL NOT NULL
);
